apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-team
  description: Team for developers
spec:
  type: team
  profile:
    email: ${your_email_used_in_github}
    picture: https://0.gravatar.com/userimage/273238023/d8c1653a7bee11bb7b21dc09624e8221?size=256
  children: []
