apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: $PROFILE_NAME
spec:
  profile: 
    # Intentional no displayName for testing
    email: $PROFILE_EMAIL
    picture: https://gravatar.com/facealways0c1cc78340
  memberOf: [team-a]
